# Generated by Django 2.0.7 on 2018-07-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ImageField(default='', upload_to='blog/%Y/%m'),
        ),
    ]
