# Generated by Django 2.0.7 on 2018-07-30 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0003_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='House_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('content_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.RemoveField(
            model_name='house',
            name='user',
        ),
        migrations.DeleteModel(
            name='House',
        ),
    ]
